// Generated by gencpp from file action_exercise/ChargingResult.msg
// DO NOT EDIT!


#ifndef ACTION_EXERCISE_MESSAGE_CHARGINGRESULT_H
#define ACTION_EXERCISE_MESSAGE_CHARGINGRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace action_exercise
{
template <class ContainerAllocator>
struct ChargingResult_
{
  typedef ChargingResult_<ContainerAllocator> Type;

  ChargingResult_()
    : header()
    , charged(false)  {
    }
  ChargingResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , charged(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _charged_type;
  _charged_type charged;





  typedef boost::shared_ptr< ::action_exercise::ChargingResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_exercise::ChargingResult_<ContainerAllocator> const> ConstPtr;

}; // struct ChargingResult_

typedef ::action_exercise::ChargingResult_<std::allocator<void> > ChargingResult;

typedef boost::shared_ptr< ::action_exercise::ChargingResult > ChargingResultPtr;
typedef boost::shared_ptr< ::action_exercise::ChargingResult const> ChargingResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_exercise::ChargingResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_exercise::ChargingResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_exercise::ChargingResult_<ContainerAllocator1> & lhs, const ::action_exercise::ChargingResult_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.charged == rhs.charged;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_exercise::ChargingResult_<ContainerAllocator1> & lhs, const ::action_exercise::ChargingResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_exercise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_exercise::ChargingResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_exercise::ChargingResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exercise::ChargingResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exercise::ChargingResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exercise::ChargingResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exercise::ChargingResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_exercise::ChargingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bc54b952d3651d1709ca5b011e23e77";
  }

  static const char* value(const ::action_exercise::ChargingResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bc54b952d3651d1ULL;
  static const uint64_t static_value2 = 0x709ca5b011e23e77ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_exercise::ChargingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_exercise/ChargingResult";
  }

  static const char* value(const ::action_exercise::ChargingResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_exercise::ChargingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"std_msgs/Header header\n"
"bool charged\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::action_exercise::ChargingResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_exercise::ChargingResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.charged);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargingResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_exercise::ChargingResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_exercise::ChargingResult_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "charged: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charged);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_EXERCISE_MESSAGE_CHARGINGRESULT_H
