// Generated by gencpp from file action_exercise/ChargingFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_EXERCISE_MESSAGE_CHARGINGFEEDBACK_H
#define ACTION_EXERCISE_MESSAGE_CHARGINGFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace action_exercise
{
template <class ContainerAllocator>
struct ChargingFeedback_
{
  typedef ChargingFeedback_<ContainerAllocator> Type;

  ChargingFeedback_()
    : header()
    , current_charge(0.0)  {
    }
  ChargingFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_charge(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _current_charge_type;
  _current_charge_type current_charge;





  typedef boost::shared_ptr< ::action_exercise::ChargingFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_exercise::ChargingFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ChargingFeedback_

typedef ::action_exercise::ChargingFeedback_<std::allocator<void> > ChargingFeedback;

typedef boost::shared_ptr< ::action_exercise::ChargingFeedback > ChargingFeedbackPtr;
typedef boost::shared_ptr< ::action_exercise::ChargingFeedback const> ChargingFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_exercise::ChargingFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_exercise::ChargingFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_exercise::ChargingFeedback_<ContainerAllocator1> & lhs, const ::action_exercise::ChargingFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.current_charge == rhs.current_charge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_exercise::ChargingFeedback_<ContainerAllocator1> & lhs, const ::action_exercise::ChargingFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_exercise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_exercise::ChargingFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exercise::ChargingFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exercise::ChargingFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d683cfa3237882538e32ec20e873407f";
  }

  static const char* value(const ::action_exercise::ChargingFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd683cfa323788253ULL;
  static const uint64_t static_value2 = 0x8e32ec20e873407fULL;
};

template<class ContainerAllocator>
struct DataType< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_exercise/ChargingFeedback";
  }

  static const char* value(const ::action_exercise::ChargingFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"std_msgs/Header header\n"
"float32 current_charge\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::action_exercise::ChargingFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_charge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargingFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_exercise::ChargingFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_exercise::ChargingFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current_charge: ";
    Printer<float>::stream(s, indent + "  ", v.current_charge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_EXERCISE_MESSAGE_CHARGINGFEEDBACK_H
