(cl:defpackage action_exercise-msg
  (:use )
  (:export
   "<CHARGINGACTION>"
   "CHARGINGACTION"
   "<CHARGINGACTIONFEEDBACK>"
   "CHARGINGACTIONFEEDBACK"
   "<CHARGINGACTIONGOAL>"
   "CHARGINGACTIONGOAL"
   "<CHARGINGACTIONRESULT>"
   "CHARGINGACTIONRESULT"
   "<CHARGINGFEEDBACK>"
   "CHARGINGFEEDBACK"
   "<CHARGINGGOAL>"
   "CHARGINGGOAL"
   "<CHARGINGRESULT>"
   "CHARGINGRESULT"
  ))

