; Auto-generated. Do not edit!


(cl:in-package action_exercise-msg)


;//! \htmlinclude ChargingResult.msg.html

(cl:defclass <ChargingResult> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (charged
    :reader charged
    :initarg :charged
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ChargingResult (<ChargingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_exercise-msg:<ChargingResult> is deprecated: use action_exercise-msg:ChargingResult instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <ChargingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_exercise-msg:header-val is deprecated.  Use action_exercise-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'charged-val :lambda-list '(m))
(cl:defmethod charged-val ((m <ChargingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_exercise-msg:charged-val is deprecated.  Use action_exercise-msg:charged instead.")
  (charged m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargingResult>) ostream)
  "Serializes a message object of type '<ChargingResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'charged) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargingResult>) istream)
  "Deserializes a message object of type '<ChargingResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
    (cl:setf (cl:slot-value msg 'charged) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargingResult>)))
  "Returns string type for a message object of type '<ChargingResult>"
  "action_exercise/ChargingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargingResult)))
  "Returns string type for a message object of type 'ChargingResult"
  "action_exercise/ChargingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargingResult>)))
  "Returns md5sum for a message object of type '<ChargingResult>"
  "6bc54b952d3651d1709ca5b011e23e77")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargingResult)))
  "Returns md5sum for a message object of type 'ChargingResult"
  "6bc54b952d3651d1709ca5b011e23e77")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargingResult>)))
  "Returns full string definition for message of type '<ChargingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Header header~%bool charged~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargingResult)))
  "Returns full string definition for message of type 'ChargingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Header header~%bool charged~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargingResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargingResult
    (cl:cons ':header (header msg))
    (cl:cons ':charged (charged msg))
))
