; Auto-generated. Do not edit!


(cl:in-package action_exercise-msg)


;//! \htmlinclude ChargingGoal.msg.html

(cl:defclass <ChargingGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_charge
    :reader goal_charge
    :initarg :goal_charge
    :type cl:float
    :initform 0.0))
)

(cl:defclass ChargingGoal (<ChargingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_exercise-msg:<ChargingGoal> is deprecated: use action_exercise-msg:ChargingGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <ChargingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_exercise-msg:header-val is deprecated.  Use action_exercise-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_charge-val :lambda-list '(m))
(cl:defmethod goal_charge-val ((m <ChargingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_exercise-msg:goal_charge-val is deprecated.  Use action_exercise-msg:goal_charge instead.")
  (goal_charge m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargingGoal>) ostream)
  "Serializes a message object of type '<ChargingGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'goal_charge))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargingGoal>) istream)
  "Deserializes a message object of type '<ChargingGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal_charge) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargingGoal>)))
  "Returns string type for a message object of type '<ChargingGoal>"
  "action_exercise/ChargingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargingGoal)))
  "Returns string type for a message object of type 'ChargingGoal"
  "action_exercise/ChargingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargingGoal>)))
  "Returns md5sum for a message object of type '<ChargingGoal>"
  "13ab596d81512dd3e9c635b92b0b401e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargingGoal)))
  "Returns md5sum for a message object of type 'ChargingGoal"
  "13ab596d81512dd3e9c635b92b0b401e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargingGoal>)))
  "Returns full string definition for message of type '<ChargingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%std_msgs/Header header~%float32 goal_charge~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargingGoal)))
  "Returns full string definition for message of type 'ChargingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%std_msgs/Header header~%float32 goal_charge~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargingGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargingGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_charge (goal_charge msg))
))
